version: '3'
services:
  age_viewer:
    image: pg:age_viewer
    container_name: age_viewer
    tty: true
    build:
      context: ./age-viewer
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_OPTIONS=--openssl-legacy-provider
      - ESLINT_NO_DEV_ERRORS=true
    dns:
      - 8.8.8.8
      - 8.8.4.4
    network_mode: "host"
    command: npm run start
